env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  'react/button-has-type': 0,
  'react/jsx-fragments': 0,
  'react/no-array-index-key': 0
}
